# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-event_map-extension}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["spanner"]
  s.date = %q{2010-10-05}
  s.description = %q{Further extends the event_calendar extension to allow easy google mapping with automatic geolocation based on event venues}
  s.email = %q{will@spanner.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/event_venues_controller.rb",
     "app/views/event_venues/_event.html.haml",
     "app/views/event_venues/_venue.html.haml",
     "app/views/event_venues/index.html.haml",
     "app/views/event_venues/index.js.erb",
     "app/views/events/_views.html.haml",
     "config/routes.rb",
     "cucumber.yml",
     "db/migrate/20100311101802_lat_long.rb",
     "db/migrate/20100311105231_get_geocodes.rb",
     "event_map_extension.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/angle_conversions.rb",
     "lib/event_map_tags.rb",
     "lib/grid_ref.rb",
     "lib/mappable.rb",
     "lib/tasks/event_map_extension_tasks.rake",
     "pkg/radiant-event_map-extension-1.0.1.gem",
     "pkg/radiant-event_map-extension-1.1.0.gem",
     "public/images/event_calendar/event_shadow.png",
     "public/images/event_calendar/one_event.png",
     "public/images/event_calendar/several_events.png",
     "public/javascript/markerclusterer.js",
     "public/stylesheets/sass/map.sass",
     "radiant-event_map-extension.gemspec",
     "spec/lib/grid_ref_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/radiant/radiant-event_map-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Google mapping for events in the radiant CMS}
  s.test_files = [
    "spec/lib/grid_ref_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<geokit>, [">= 0"])
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<radiant-event_calendar-extension>, [">= 0"])
    else
      s.add_dependency(%q<geokit>, [">= 0"])
      s.add_dependency(%q<radiant>, [">= 0.9.0"])
      s.add_dependency(%q<radiant-event_calendar-extension>, [">= 0"])
    end
  else
    s.add_dependency(%q<geokit>, [">= 0"])
    s.add_dependency(%q<radiant>, [">= 0.9.0"])
    s.add_dependency(%q<radiant-event_calendar-extension>, [">= 0"])
  end
end

